<?php
/**
 * @author 18th DigiTech Team
 * @copyright Copyright (c) 2022 18th DigiTech (https://www.18thdigitech.com)
 * @package Eighteentech_Buildbox
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**  @var $block \Magento\Checkout\Block\Cart\Grid */

$isBoxFound = $storeSize = $pos = $i = $index = $productId= 0;
$checkLoop=1;
$ifSize = true;
$onlyOneType= $checkOption = $stopLoop = 'yes';

$itemSize = $arrIndex = [];
$boxItemId = $boxItemIdkit = $simpleBoxRem = $InSimpleProBoxItemId= '';

?>
<?php $mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "<?= $block->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }'
          class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
        <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
            <?php if ($block->getPagerHtml()): ?>
                <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                    data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption class="table-caption"><?= $block->escapeHtml(__('Shopping Cart Items')) ?></caption>
            
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= $block->escapeHtml(__('Item')) ?></span></th>
                    <th class="col price" scope="col"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
                    <th class="col-price cgst"><?php /* @escapeNotVerified */ echo __('CGST') ?></th>
                    <th class="col-price sgst"><?php /* @escapeNotVerified */ echo __('SGST / UTGST') ?></th>
                    <th class="col-price igst"><?php /* @escapeNotVerified */ echo __('IGST') ?></th>               
                    <th class="col qty" scope="col"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
                    <th class="col subtotal" scope="col"><span><?= $block->escapeHtml(__('Subtotal')) ?></span></th>
                </tr>
            </thead>
                
            <?php 
            $cartigst=0;
            $cartsgst=0;
            $cartcgst=0;
            foreach ($block->getItems() as $_item):

                $kitProSize = $_item->getKitProductSize();
                if($_item->getBoxId() == 1){
                    $kitBoxName = $_item->getBoxName();
                }
                if($kitProSize != ''){
                    $itemSize[] = explode(",",$kitProSize);
                }
                    if ($_item->getBoxId() != '1') {?>
                        <?= $block->getItemHtml($_item) ?>
                <?php } else {
                        $isBoxFound++;
                }  
                $cartigst += $_item->getIgstAmount();
                $cartsgst += $_item->getSgstAmount(); 
                $cartcgst += $_item->getCgstAmount();         
            endforeach ?>
        </table>

        <?php if ($isBoxFound > 0): ?>
            <table id="shopping-box-table" class="box"><?php 
                $i = 0;

                foreach ($block->getItems() as $_items): 
                   
                    if($_items->getKitProductSize() == ''){ 
                                              
                        if ($_items->getBoxId() == 1 && $_items->getBoxType() != 'yes') {?>

                        <tbody class="simple_porduct_box_section index-<?= $i?>">
                            <tr>
                                <td colspan="7">
                                <h2 class="item-inbox"><?= $block->escapeHtml(__('Items In Box')) ?></h2>
                                </td>
                            </tr>

                            <tr>
                                <td>   
                                    <div class="box-name-sections">
                                        <div class="box-pro-image">
                                            <div class="pro-image">
                                                <?php if($_items->getBoxId() == 1){ ?>
                                                <?= $block->getProductImage($_items->getProductId())?>
                                                <?php } ?>
                                            </div>
                                        </div>
                                        <div class="box-pro-edit">
                                            <div class="BoxName"> 
                                                <div class="box_name_section12"> 
                                                    <span class="box-name">
                                                        <?= /* @noEscape */ $_items->getBoxName()?>
                                                        <input type="hidden" name="box-name" 
                                                        value="<?= /* @noEscape */ $_items->getBoxName()?>"/>
                                                    </span>
                                                    <span id="name-pop-show" class="editName" style="display: none;">
                                                        <?= /* @noEscape */ __('Edit') ?>
                                                        <input type="hidden" name="edit-box-name-proid" class="edit-box-name-proid"
                                                        value="<?= /* @noEscape */ $_items->getProductId()?>"
                                                        prodItemId="<?= /* @noEscape */ $_items->getItemId()?>"
                                                        boxTitle="<?= /* @noEscape */ $_items->getBoxName()?>"/>
                                                    </span>                                       
                                                </div>
                                            </div>
                                            <?php 
                                                $simpleBoxRem = $_items->getItemId();
                                            ?>
                                            <div class="edit simple_box_edit">                 
                                                <a href="#" id="<?= /* @noEscape */ $_items->getItemId() ?>" 
                                                class="box-edit">
                                                    <?= /* @noEscape */ __('Edit')?>
                                                    <input
                                                        type="hidden"
                                                        name="boxName" 
                                                        class="boxName"
                                                        value="<?= /* @noEscape */ $_items->getBoxName() ?>"
                                                    >
                                                    <input
                                                        type="hidden" 
                                                        name="editProId" 
                                                        class="editProId" 
                                                        value="<?= /* @noEscape */ $_items->getProductId() ?>" 
                                                        prodItemId="<?= /* @noEscape */ $_items->getItemId() ?>"
                                                    />
                                                    
                                                    <input
                                                        type="hidden"
                                                        name="boxId"
                                                        class="boxId"
                                                        value="<?= /* @noEscape */ $_items->getId() ?>"
                                                        editProQty="<?= /* @noEscape */ $_items->getQty() ?>"
                                                    >
                                                    <input
                                                        type="hidden"
                                                        name="boxDimentions"
                                                        class="boxDimentions"
                                                        value="<?= /* @noEscape */ $_items->getProductDim() ?>"
                                                    >
                                                    <?= /* @noEscape */ $_items->getBoxweight() ?>
                                                </a>
                                            </div>
                                            <div class="field qty">
                                                <div class="control qty">
                                                    <label for="cart-<?= $_items->getItemId()?>-qty">
                                                        <input
                                                            id="cart-<?= $_items->getItemId()?>-qty"
                                                            name="cart[<?= $_items->getItemId()?>][qty]"
                                                            value="<?= $_items->getQty()?>"
                                                            type="hidden"
                                                            size="4"
                                                            step="any" 
                                                            title="Qty"
                                                            class="input-text qty"                                                    
                                                            data-item-qty="<?= $_items->getQty()?>"
                                                            data-role="cart-item-qty"
                                                        >
                                                    </label>
                                                </div>
                                            </div>
                                        </div>                                        
                                    </div> 
                                    
                                </td>
                                <td><span class="simpleTotBoxPrice">0</span></td>
                                <td><span class="totcgst<?= /* @noEscape */ $index?>"><?= /* @noEscape */ $block->formatPrice($cartcgst, true)?></span></td>
                                <td><span class="totsgst<?= /* @noEscape */ $index?>"><?= /* @noEscape */ $block->formatPrice($cartsgst, true)?></span></td>
                                <td><span class="totigst<?= /* @noEscape */ $index?>"><?= /* @noEscape */ $block->formatPrice($cartigst, true)?></span></td>
                                <td class="col qty"> 
                                    <span class="totKitQty" cartqty="<?= /* @noEscape */ $_items->getQty()?>">
                                        <?= /* @noEscape */ $_items->getQty()?>
                                    </span>                                    
                                </td>
                                <td><span class="simpleGrandTotBoxPrice">0</span></td>
                            </tr> 

                            <tr>
                                <td colspan="7"><hr/></td>
                            </tr>

                            <!-- show kit simple product  -->
                            <tr id="box_for_simple-<?= /* @noEscape */ $_items->getItemId()?>">
                                <?php $InSimpleProBoxItemId = $_items->getItemId();?>
                                <td class="col name">
                                    <div class="box-items">

                                        <div class="box-cart-image">
                                            <div class="pro-image">
                                                <?= $block->getProductImage($_item->getProductId())?>
                                            </div>                                            
                                        </div> 
                                        
                                        <div class="cart_item_details">
                                            <div class="box-details">

                                                <div class="box-item-name box-product">                     
                                                    <h4><?= /* @noEscape */ $_items->getName()?> </h4>
                                                </div>                                                
                                                <?php                                               
                                                    // get custom options value of cart items
                                                    $options = $_items->getProduct()->getTypeInstance(true)->getOrderOptions($_items->getProduct());
                                                    
                                                    if(isset($options['attributes_info'])){
                                                        foreach($options['attributes_info'] as $option){?>
                                                            <div class="box_custom_option">
                                                                <span class="option_label"><?= $option['label']?>: </span>
                                                                <span class="option_value"><?= $option['value']?></span>
                                                            </div><?php
                                                        }                                                       
                                                    }
                                                       
                                                    $additionalOptions = $_items->getOptionByCode('info_buyRequest');
                                                    $buyRequest =$additionalOptions->getValue();
                                                
                                                    $itemList = json_decode($buyRequest, true);
                                                    $imgPath  = '';
                                                    $imgtitle = '';

                                                    if (!empty($itemList['options'])) {

                                                        foreach ($itemList['options'] as $getOptions) {                                                                                        
                                                            if (isset($getOptions['title']) || isset($getOptions['quote_path'])) {
                                                                $imgtitle = $getOptions['title'];
                                                                $imgPath = $getOptions['quote_path'];
                                                            }                                                                   
                                                        }

                                                        if ($imgPath != '') {?> 

                                                            <div class="kit-box-logo">
                                                                <span class="logo-title"><?= /* @noEscape */ __('Logo:')?></span>
                                                                <a href="<?= /* @noEscape */ '/media/'.$imgPath ?>" target="_blank">
                                                                    <?= /* @noEscape */ $imgtitle ?>
                                                                </a>
                                                            </div><?php

                                                            $addonPrice = '';
                                                            if($_items->getKitAddonPrice() != ''){
                                                                $addonPrice = $_items->getKitAddonPrice();
                                                            }

                                                            if($addonPrice != ''){ ?>
                                                                <div class="kit-addon-price .container-row">
                                                                    <span class="title">Addon price: </span><?= /* @noEscape */ ": ". $block->formatPrice($addonPrice,true)?>
                                                                </div><?php
                                                            }
                                                        }
                                                    } 
                                                    $sizecartigst=0;
                                                    $sizecartsgst=0;
                                                    $sizecartcgst=0;
                                                ?>
                                            </div> 
                                        
                                            <div class="box-edit-action">                     
                                                <h4 id="removeBtn" class="removeBtn" boxItemId="<?= /* @noEscape */ $simpleBoxRem?>" >
                                                    <span><?= /* @noEscape */ __('Remove')?></span> 
                                                </h4>
                                            </div>  

                                        </div>
                                    </div>                                
                                </td>

                                <td class="col price">
                                    <span class="cart_calculation cart_prodprice_num" cartPrice="<?= /* @noEscape */ $_items->getPrice() + +  $_items->getKitAddonPrice()?>">
                                    <?= /* @noEscape */ $block->formatPrice(($_items->getPrice() +  $_items->getKitAddonPrice()),true)?>
                                    </span>
                                </td>

                                <td class="col-price cgst" data-th="<?php echo $block->escapeHtml(__('CGST')); ?>">
                                    <span class="price"><?= /* @noEscape */ $block->formatPrice($sizecartcgst,true) ?></span><br>Rate:<?php echo round($_items->getCgstPercent() ?? 0,2);?>%
                                </td>
                            
                                <?php
                                    $sgstUtgstPercent=0;
                                    $sgstUtgstAmount=0;
                                    if($_item->getSgstPercent()>0){
                                        $sgstUtgstPercent=$_items->getSgstPercent();
                                        $sgstUtgstAmount=$_items->getSgstAmount();
                                    }
                                    else{
                                        $sgstUtgstPercent=$_items->getUtgstPercent();
                                        $sgstUtgstAmount=$_items->getUtgstAmount();
                                    }
                                ?>

                                <td class="col-price sgst" data-th="<?= $block->escapeHtml(__('SGST')); ?>">
                                    <span class="price"><?= /* @noEscape */ $block->formatPrice($sizecartsgst,true) ?></span><br>Rate:<?php echo round($sgstUtgstPercent ?? 0,2);?>%
                                </td>

                                <td class="col-price" data-th="<?= $block->escapeHtml(__('IGST')); ?>">
                                    <span class="price igst"><?= /* @noEscape */ $block->formatPrice($sizecartigst,true) ?></span><br>Rate:<?php echo round($_items->getIgstPercent() ?? 0,2);?>%</td>

                                <td class="col qty">
                                    <span class="cart_calculation cart_prodqty_num" cartqty="<?= $_items->getProductQtyEachBox() ?? 1?>">
                                    <?= /* @noEscape */ $_items->getProductQtyEachBox()?>
                                    </span>
                                </td>

                                <td class="col subtotal">
                                    <span class="cart_prod_totprice">
                                        <?= /* @noEscape */ $block->formatPrice( $_items->getProductQtyEachBox() * ($_items->getPrice() +  $_items->getKitAddonPrice()) )?>
                                    </span>
                                </td>
                            </tr>

                      

                            <?php 
                            if ($_items->getBoxId() == 1 ) {
                                foreach ($block->getItems() as $kitProItem) {

                                    if($kitProItem->getBoxId() != 1 && $kitProItem->getProductType() != 'configurable'){
                                    if ($kitProItem->getBoxItemId() == $InSimpleProBoxItemId && $kitProItem->getBoxItemId() != ''){
                                        ?>
                                        <tr class="item-box item">
                                            <td class="col item">

                                                <div class="box-items">
                                                    <?php
                                                        // $objectmanager = \Magento\Framework\App\ObjectManager::getInstance();
                                                        // $product_id = $kitProItem->getProductId();
                                                        // $product = $objectmanager ->create(\Magento\Catalog\Model\Product::class)
                                                        // ->load($product_id);
                                                        // $productimages = $product->getMediaGalleryImages();
                                                    
                                                    ?>

                                                    <div class="box-cart-image product-item-photo">
                                                        <div class="pro-image"> 
                                                            <?= $block->getProductImage($kitProItem->getProductId());?>
                                                        </div>
                                                     
                                                    </div> 
                                                    <div class="cart_item_details">                                
                                                        <div class="box-item-name">                     
                                                            <h4><?= /* @noEscape */ $kitProItem->getName() ?></h4>
                                                        </div> 
                                                    </div>
                                                </div>
                                            </td>

                                            <td class="col price">                        
                                                <span class="cart_calculation cart_prodprice_num" cartprice="<?= $kitProItem->getPrice()?>">
                                                    <?= /* @noEscape */ $block->formatPrice($kitProItem->getPrice(), true) ?>
                                                </span>                        
                                            </td>

                                            <td class="col-price cgst" data-th="<?php echo $block->escapeHtml(__('CGST')); ?>">
                                                <span class="price"><?= /* @noEscape */ $block->formatPrice($kitProItem->getData('cgst_amount'),true) ?></span><br>Rate:<?php echo round($kitProItem->getCgstPercent() ?? 0,2);?>%
                                            </td><?php

                                            $sgstUtgstPercent=0;
                                            $sgstUtgstAmount=0;
                                            if($kitProItem->getSgstPercent()>0){
                                                $sgstUtgstPercent=$kitProItem->getSgstPercent();
                                                $sgstUtgstAmount=$kitProItem->getSgstAmount();
                                            }
                                            else{
                                                $sgstUtgstPercent=$kitProItem->getUtgstPercent();
                                                $sgstUtgstAmount=$kitProItem->getUtgstAmount();
                                            }?>

                                            <td class="col-price sgst" data-th="<?php echo $block->escapeHtml(__('SGST')); ?>">
                                                <span class="price"><?= /* @noEscape */ $block->formatPrice($sgstUtgstAmount,true) ?></span><br>Rate:<?php echo round($sgstUtgstPercent ?? 0,2);?>%
                                            </td>

                                            <td class="col-price" data-th="<?php echo $block->escapeHtml(__('IGST')); ?>">
                                                <span class="price igst"><?= /* @noEscape */ $block->formatPrice($kitProItem->getData('igst_amount'),true) ?></span><br>Rate:<?php echo round($kitProItem->getIgstPercent() ?? 0,2);?>%
                                            </td>
                                                
                                            <td class="col qty">
                                                <span class="cart_calculation cart_prodqty_num" cartqty="<?= $kitProItem->getProductQtyEachBox()?>">
                                                    <?= /* @noEscape */ $kitProItem->getProductQtyEachBox()?>
                                                </span>
                                            </td>

                                            <td class="col subtotal">
                                                <span class="cart_prod_totprice">
                                                    <?= /* @noEscape */ $block->formatPrice( ( $kitProItem->getProductQtyEachBox() * $kitProItem->getPrice() ),true)?>
                                                </span>
                                            </td>
                                        </tr>
                                    <?php } 
                                    }
                                }
                            } ?>

                        </tbody><?php
                        $i++;
                    } 
                  
                    }else{

                       // Show configurable product which in kit 
                       
                    if ($_items->getKitProductSize() != '' && $onlyOneType=='yes') {                      
                        $KItemId = '';
                        $productItemId = '';
                        $configKitPro = '';
                        
                        if($_items->getBoxId() == 1){                                    
                            $productId= $_items->getProductId();
                            $productItemId= $_items->getItemId();

                        }
                        $pos++;
                        $storeSize = $_items->getKitProductSize();?>
                        <tbody class="configurable_box_section" postion="<?= $pos ?>">
                        <tr>
                            <td colspan="7">
                                <h2 class="item-inbox"><?= $block->escapeHtml(__('Items In Box')) ?></h2>
                            </td>
                        </tr>

                        <tr>
                            <td>

                            <?php foreach($block->getItems() as $configItem){

                                if($productItemId != $configItem->getBoxItemId() && $configItem->getBoxType() == 'yes' && $configItem->getKitProductSize() == ''){
                                    if($configItem->getBoxId() == 1 && $_items->getBoxType() == 'yes'){
                                        $KItemId = $configItem->getItemId();?>

                                        <div class="box-name-sections">
                                            <div class="box-pro-image">
                                                <div class="pro-image">
                                                    <?php if($configItem->getBoxId() == 1){ ?>
                                                    <?= $block->getProductImage($configItem->getProductId())?>
                                                    <?php } ?>
                                                </div>
                                            </div>

                                            <div class="product_edit box-pro-edit">                               
                                                <div class="BoxName"> 
                                                    <?= $configItem->getBoxName()?>
                                                    <span id="box-name" style="display:none">
                                                    <?= /* @noEscape */ $kitBoxName ."-". $storeSize ?>
                                                    <input type="hidden" name="box-name" 
                                                    value="<?= /* @noEscape */ $configItem->getBoxName() ?>"/>
                                                    </span>
                                                </div>
                                                <?php $boxItemIdkit = $configItem->getItemId()?>
                                                <div class="edit configurable_box_edit">                 
                                                    <a href="#" id="<?= /* @noEscape */ $configItem->getItemId() ?>" 
                                                    class="box-edit">
                                                        <?= /* @noEscape */ __('Edit')?>
                                                        <input
                                                            type="hidden"
                                                            name="boxName" 
                                                            class="boxName"
                                                            value="<?= /* @noEscape */ $configItem->getBoxName() ?>"
                                                        >
                                                        <input
                                                            type="hidden" 
                                                            name="editProId" 
                                                            class="editProId" 
                                                            value="<?= /* @noEscape */ $configItem->getProductId() ?>" 
                                                            prodItemId="<?= /* @noEscape */ $configItem->getItemId() ?>"
                                                        />
                                                        
                                                        <input
                                                            type="hidden"
                                                            name="boxId"
                                                            class="boxId"
                                                            value="<?= /* @noEscape */ $configItem->getId() ?>"
                                                            editProQty="<?= /* @noEscape */ $configItem->getQty() ?>"
                                                        >
                                                        <input
                                                            type="hidden"
                                                            name="boxDimentions"
                                                            class="boxDimentions"
                                                            value="<?= /* @noEscape */ $configItem->getProductDim() ?>"
                                                        >
                                                        <?= /* @noEscape */ $configItem->getBoxweight() ?>
                                                    </a>
                                                </div>
                                            </div>
                                            
                                        </div> <?php
                                    }
                                }
                                }?>
                            </td>
                            <td><span class="totBoxPrice">0</span></td>
                            <td><span class="totcgst<?= /* @noEscape */ $index?>"><?= /* @noEscape */ $block->formatPrice($cartcgst, true)?></span></td>
                            <td><span class="totsgst<?= /* @noEscape */ $index?>"><?= /* @noEscape */ $block->formatPrice($cartsgst, true)?></span></td>
                            <td><span class="totigst<?= /* @noEscape */ $index?>"><?= /* @noEscape */ $block->formatPrice($cartigst, true)?></span></td>
                            <td class="col qty"> 
                                <span class="totKitQty2" cartQty="<?= /* @noEscape */ $_item->getQty()?>">
                                    <?= /* @noEscape */ $_item->getQty()?>
                                </span> 
                                
                            </td>
                            <td><span class="grandTotBoxPrice">0</span></td>
                        </tr> 
                        <tr>
                           <td colspan="7"><hr/></td>
                        </tr>
                        <tr>
                            <td class="col name">
                                <div class="box-items">
                                   <div class="box-cart-image">
                                        <div class="pro-image">
                                            <?= $block->getProductImage($_items->getProductId())?>
                                        </div>                                            
                                    </div> 
                                
                                    <div class="cart_item_details">
                                        <div class="box-details">
                                            <div class="box-item-name <?= /* @noEscape */ $_items->getProductType()?>">
                                                <h4><?= /* @noEscape */ $_items->getName()?> </h4>
                                            </div>
                                            <table>
                                                <tr>
                                                    <th>
                                                        <span class="cart_size_title">Size</span>
                                                    </th>
                                                    <th>
                                                        <span class="cart_qty_title">Box Qty</span>
                                                    </th>
                                                  <!--  <th>
                                                        <span class="cart_price_title">Price</span>
                                                    </th>-->
                                                </tr><?php
                                                    $sizecartigst=0;
                                                    $sizecartsgst=0;
                                                    $sizecartcgst=0;
                                                    foreach ($block->getItems() as $_childItem){                                        
                                                        if($_childItem->getKitProductSize() != ''){
                                                            $storeSize = $_childItem->getKitProductSize(); 
                                                            $sizecartigst += $_childItem->getIgstAmount();
                                                                $sizecartsgst += $_childItem->getSgstAmount(); 
                                                                $sizecartcgst += $_childItem->getCgstAmount();    
                                                            ?>                                              
                                                            <tr>
                                                                <td class="cartConfigLabel" confQty="<?= /* @noEscape */ $storeSize?>">
                                                                    <?= /* @noEscape */ $storeSize?>
                                                                </td>
                                                                <td class="cartConfigQty" cartqty="<?= /* @noEscape */ $_childItem->getQty()?>">
                                                                    <?= /* @noEscape */ $_childItem->getQty()?>                                                                    
                                                                    <div class="field qty">
                                                                        <div class="control qty">
                                                                            <label for="cart-<?= $_childItem->getItemId()?>-qty">                                                                        
                                                                                <input 
                                                                                    id="cart-<?= /* @noEscape */ $_childItem->getItemId()?>-qty" 
                                                                                    name="cart[<?= /* @noEscape */ $_childItem->getItemId()?>][qty]"
                                                                                    value="<?= /* @noEscape */ $_childItem->getQty()?>"
                                                                                    type="hidden"
                                                                                    class="input-text qty"
                                                                                    data-item-qty="<?= /* @noEscape */ $_childItem->getQty()?>"
                                                                                    data-role="cart-item-qty"
                                                                                >
                                                                            </label>
                                                                        </div>
                                                                    </div>
                                                                </td>
                                                            <!--  <td class="cartConfigPrice-<?//= $i ?>" cartPrice="<?//= $_childItem->getPrice()?>">
                                                                    <?//= /* @noEscape */ $block->formatPrice($_childItem->getPrice(),true)?>
                                                                </td>-->
                                                            </tr><?php
                                                            $i++;
                                                        } 
                                                    }?>
                                            </table>
                                        </div> 
                      
                                        <div class="box-edit-action">                     
                                            <h4 id="removeBtn" class="removeBtn" boxItemId="<?= $boxItemIdkit ?>" ><span>Remove</span> </h4>
                                        </div>                               
                                    </div>
                                </div>                                
                            </td>
                            <td class="col price">
                                <span class="cart_conf_prodprice_num" cartPrice="<?= /* @noEscape */ $_items->getPrice()?>">
                                 <?= /* @noEscape */ $block->formatPrice($_items->getPrice(),true)?>
                                </span>
                            </td>

                            <td class="col-price cgst" data-th="<?php echo $block->escapeHtml(__('CGST')); ?>">
                                <span class="price"><?= /* @noEscape */ $block->formatPrice($sizecartcgst,true) ?></span><br>Rate:<?php echo round($_items->getCgstPercent() ?? 0,2);?>%
                            </td>
                           
                            <?php
                                $sgstUtgstPercent=0;
                                $sgstUtgstAmount=0;
                                if($_item->getSgstPercent()>0){
                                    $sgstUtgstPercent=$_items->getSgstPercent();
                                    $sgstUtgstAmount=$_items->getSgstAmount();
                                }
                                else{
                                    $sgstUtgstPercent=$_items->getUtgstPercent();
                                    $sgstUtgstAmount=$_items->getUtgstAmount();
                                }
                            ?>
                            <td class="col-price sgst" data-th="<?= $block->escapeHtml(__('SGST')); ?>">
                            <span class="price"><?= /* @noEscape */ $block->formatPrice($sizecartsgst,true) ?></span><br>Rate:<?php echo round($sgstUtgstPercent ?? 0,2);?>%
                            </td>
                            <td class="col-price" data-th="<?= $block->escapeHtml(__('IGST')); ?>">
                                <span class="price igst"><?= /* @noEscape */ $block->formatPrice($sizecartigst,true) ?></span><br>Rate:<?php echo round($_items->getIgstPercent() ?? 0,2);?>%</td>
                            <td class="col qty">
                                <span class="cart_prodeachqty">
                                   <?= /* @noEscape */ $_items->getProductQtyEachBox()?>
                                </span>
                            </td>
                            <td class="col subtotal">
                                <span class="cart_prod_totprice">
                                    <?= /* @noEscape */ $block->formatPrice( $_items->getProductQtyEachBox() * $_items->getPrice() )?>
                                </span>
                            </td>
                        </tr><?php 
                        $onlyOneType = 'no';
                    }
                    
                    /**
                     * Show simple product which in kit 
                     **/                   
                    $storeItemId = [];
                    $kitBoxitemId = 0;
                    $productItemId = 0;
                    if($checkLoop == 1){
                        foreach ($block->getItems() as $item) {
                           
                            if($item->getBoxType() == 'yes' && $item->getKitProductSize() == ''){
                                if($item->getBoxId() == 1){                                    
                                    $productId= $item->getProductId();
                                    $productItemId= $item->getItemId();
                                    $boxId = $item->getBoxId();

                                }
                                // $quoteItems = $quote->getAllVisibleItems();
                                foreach($block->getItems() as $quoteItem){
              
                                    if($productItemId == $quoteItem->getBoxItemId() && $quoteItem->getBoxType() == 'yes' && $quoteItem->getKitProductSize() == ''){
                                            
                                        if((empty($storeItemId) || !in_array($quoteItem->getItemId(),$storeItemId))){
                                            $storeItemId[] =  $quoteItem->getItemId(); ?>
                                            <!-- this section to add kit in configurable product  -->
                                            <tr>
                                                <td class="col name">
                                                    <div class="box-items">                             
                                                        <div class="box-cart-image">
                                                            <div class="pro-image">
                                                                <?= $proImage= $block->getProductImage($quoteItem->getProductId())?>
                                                            </div>                                            
                                                        </div> 
                                                    
                                                        <div class="cart_item_details">
                                                            <div class="box-details">
                                                                <div class="box-item-name"><?php
                                                                    if( $quoteItem->getBoxId() == 1 ){?>

                                                                        <h4 id="confBoxId" confBoxsId="<?= /* @noEscape */ $quoteItem->getId()?>">
                                                                            <?= /* @noEscape */ $quoteItem->getName() ?>                                                                        
                                                                        </h4><?php
                                                                        
                                                                        $options = $quoteItem->getProduct()->getTypeInstance(true)->getOrderOptions($quoteItem->getProduct());
                                                                    
                                                                        if(isset($options['attributes_info'])){
                                                                            foreach($options['attributes_info'] as $option){?>
                                                                                <div class="box_custom_option">
                                                                                    <span class="option_label"><?= $option['label']?>: </span>
                                                                                    <span class="option_value"><?= $option['value']?></span>
                                                                                </div><?php
                                                                            }                                                       
                                                                        }                                                                               
                                                                         
                                                                        // get box logo
                                                                        $additionalOptions = $quoteItem->getOptionByCode('info_buyRequest');
                                                                        $buyRequest =$additionalOptions->getValue();
                                                                    
                                                                        $itemList = json_decode($buyRequest, true);
                                                                        $imgPath  = '';
                                                                        $imgtitle = '';
                                                                        if (!empty($itemList['options'])) {
                                                                            foreach ($itemList['options'] as $getOptions) {                                                                                        
                                                                                if (isset($getOptions['title']) || isset($getOptions['quote_path'])) {
                                                                                    $imgtitle = $getOptions['title'];
                                                                                    $imgPath = $getOptions['quote_path'];
                                                                                }                                                                   
                                                                            }
                                                                            if ($imgPath != '') {?>

                                                                                <div class="kit-box-logo">
                                                                                    <span class="logo-title"><?= /* @noEscape */ __('Logo:')?></span>
                                                                                    <a href="<?= /* @noEscape */ '/media/'.$imgPath ?>" target="_blank">
                                                                                        <?= /* @noEscape */ $imgtitle ?>
                                                                                    </a>
                                                                                </div><?php

                                                                                $addonPrice = '';
                                                                                if($quoteItem->getKitAddonPrice() != ''){
                                                                                    $addonPrice = $quoteItem->getKitAddonPrice();
                                                                                }
                                                                                if($addonPrice != ''){ ?>
                                                                                    <div class="kit-addon-price .container-row">
                                                                                        <span class="title">Addon price: </span><?= /* @noEscape */ ": "./* @noEscape */ $block->formatPrice($addonPrice, true)?>
                                                                                    </div><?php
                                                                                }
                                                                            }
                                                                        }
                                                                    } else { ?>                 
                                                                        <h4 class="product-name">
                                                                            <?= /* @noEscape */ $quoteItem->getName()?>
                                                                        </h4> <?php
                                                                    } ?>
                                                                </div>                            
                                                            </div>                                
                                                        </div>
                                                    </div>                                
                                                </td>
                                                <?php 
                                                    $addonPrice = '';
                                                    if($quoteItem->getKitAddonPrice() != ''){
                                                        $addonPrice = (int)$quoteItem->getKitAddonPrice()+(int)$quoteItem->getPrice();
                                                    }else{
                                                        $addonPrice= $quoteItem->getPrice();
                                                    }?>  
                                                
                                                <td class="col price">
                                                    <span class="cart_conf_prodprice_num" cartPrice="<?= $addonPrice ?>">
                                                    <?= /* @noEscape */ $block->formatPrice($addonPrice,true) ?>
                                                    </span>
                                                </td>

                                                <td class="col-price cgst" data-th="<?= $block->escapeHtml(__('CGST')); ?>">
                                                <span class="price"><?= /* @noEscape */ $block->formatPrice($quoteItem->getData('cgst_amount'),true) ?></span><br>Rate:<?php echo round($quoteItem->getCgstPercent() ?? 0,2);?>%
                                                </td><?php
                                                $sgstUtgstPercent=0;
                                                $sgstUtgstAmount=0;
                                                if($_item->getSgstPercent()>0){
                                                    $sgstUtgstPercent=$quoteItem->getSgstPercent();
                                                    $sgstUtgstAmount=$quoteItem->getSgstAmount();
                                                }
                                                else{
                                                    $sgstUtgstPercent=$_item->getUtgstPercent();
                                                    $sgstUtgstAmount=$_item->getUtgstAmount();
                                                }?>
                                                <td class="col-price sgst" data-th="<?= $block->escapeHtml(__('SGST')); ?>">
                                                <span class="price"><?= /* @noEscape */ $block->formatPrice($sgstUtgstAmount,true) ?></span><br>Rate:<?php echo round($sgstUtgstPercent ?? 0,2);?>%
                                                </td>
                                                <td class="col-price" data-th="<?= $block->escapeHtml(__('IGST')); ?>">
                                                    <span class="price igst"><?= /* @noEscape */ $block->formatPrice($quoteItem->getData('igst_amount'),true) ?></span><br>Rate:<?php echo round($quoteItem->getIgstPercent() ?? 0,2);?>%</td>
                                                <td class="col qty">
                                                    <span class="cart_prod_eachqty">
                                                    <?= /* @noEscape */ $qty = $quoteItem->getProductQtyEachBox() == null ? 1 : $quoteItem->getProductQtyEachBox()?>
                                                    </span>
                                                </td>
                                                <?php 
                                                    $addonPrice = '';
                                                    if($quoteItem->getKitAddonPrice() != ''){
                                                        $addonPrice = (int)$quoteItem->getKitAddonPrice()+(int)$quoteItem->getPrice();
                                                    }else{
                                                        $addonPrice= $quoteItem->getPrice();
                                                    }?> 
                                                <td class="col subtotal">
                                                    <span class="cart_prod_totprice">
                                                        <?php ?>
                                                        <?= /* @noEscape */ $block->formatPrice( $qty * $addonPrice )?>
                                                    </span>
                                                </td>
                                            </tr><?php
                                        }
                                    }
                                }?>

                                <div class="actions-toolbar">                
                                    <?= /* @noEscape */ $block->getActions($_item) ?>
                                </div><?php
                            }
                        }
                    }
                    
                    $checkLoop=0;                       
                    $arrIndex[]= $index;
                    $index++;
                }
                endforeach;?>

                <input type="hidden" value="<?= count($arrIndex)?>" id="arrIndex"/>
            </table>
        <?php endif ?>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                 data-attribute="cart-products-toolbar-bottom">
                 <?= /* @noEscape */ $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?= /* @noEscape */ $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= /* @noEscape */ $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= /* @noEscape */
                $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        <?php endif; ?>
        <?php if ($block->getViewModel()->isClearShoppingCartEnabled()): ?>
            <button type="button"
                    name="update_cart_action"
                    data-cart-empty=""
                    value="empty_cart"
                    title="<?= /* @noEscape */
                    $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                    class="action clear" id="empty_cart_button">
                <span><?= /* @noEscape */ $block->escapeHtml(__('Clear Shopping Cart')) ?></span>
            </button>
        <?php endif ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= /* @noEscape */
                $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update">
            <span><?= /* @noEscape */ $block->escapeHtml(__('Update Shopping Cart')) ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" 
        data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>
