<?php
    /**
     * @author 18th DigiTech Team
     * @copyright Copyright (c) 2022 18th DigiTech (https://www.18thdigitech.com)
     * @package Eighteentech_CustomForm
     */
?>
<div class="main-container">
    <div class="coming-soon">
        <h2><?= /** @noEscape */ __('coming soon')?></h2>
        <div class="first-dibs-section">
            <h1><?= /** @noEscape */ __('First Dibs')?></h1>
            <div class="countDown-section">
                <div id="timer">                    
                    <div id="days" class="countdown-timer"></div>
                    <div id="hours" class="countdown-timer"></div>
                    <div id="minutes" class="countdown-timer"></div>
                    <div id="seconds" class="countdown-timer"></div>
                </div>
            </div>
            <div >
                <a href="/customform/index/signform"><?= /** @noEscape */ __('Sign Up')?></a>
            </div>
        </div>
    </div>
</div>

<script>
  
require(['jquery', 'jquery/ui'], function($){
  jQuery(document).ready( function() {    
    function makeTimer() {
        // var endTime = new Date("29 April 2018 9:56:00 GMT+01:00");	
        var endTime = new Date("<?= $block->countDownDate()?>");			
        endTime = (Date.parse(endTime) / 1000);

        var now = new Date();
        now = (Date.parse(now) / 1000);

        var timeLeft = endTime - now;

        var days = Math.floor(timeLeft / 86400); 
        var hours = Math.floor((timeLeft - (days * 86400)) / 3600);
        var minutes = Math.floor((timeLeft - (days * 86400) - (hours * 3600 )) / 60);
        var seconds = Math.floor((timeLeft - (days * 86400) - (hours * 3600) - (minutes * 60)));

        if (hours < "10") { hours = "0" + hours; }
        if (minutes < "10") { minutes = "0" + minutes; }
        if (seconds < "10") { seconds = "0" + seconds; }

        $("#days").html(days +":"+ "<span>Days</span>");
        $("#hours").html(hours +":"+ "<span>Hours</span>");
        $("#minutes").html(minutes +":"+ "<span>Minutes</span>");
        $("#seconds").html(seconds + "<span>Seconds</span>");		

    }setInterval(function() { makeTimer(); }, 1000);


  });
});

</script>