<?php
/**
 * @author 18th DigiTech Team
 * @copyright Copyright (c) 2022 18th DigiTech (https://www.18thdigitech.com)
 * @package Eighteentech_CustomForm
 */
?>

<?php
if ($block->isEnable()): ?>
<div class="masthead CommingsoonPage">
	<div class="masthead-content text-black signform">
		<?= $this->getLayout()
			->createBlock('Magento\Cms\Block\Block')
			->setBlockId('coming_soon')
			->toHtml();
		?>
		<div class="masthead-countdown-form">
			<div class="main-container" id="comingSoonId">
				<div class="coming-soon">
					<h2><?=/** @noEscape */__('coming soon')?></h2>
					<div class="first-dibs-section">
						<h1><?=/** @noEscape */__('First Dibs')?></h1>
						<div class="countDown-section">
							<div id="timer">
								<div id="days" class="countdown-timer">00:<span>Days</span></div>
								<div id="hours" class="countdown-timer">00:<span>Hours</span></div>
								<div id="minutes" class="countdown-timer">00:<span>Minutes</span></div>
								<div id="seconds" class="countdown-timer">00<span>Minutes</span></div>
							</div>
						</div>

						<div class="signup-btn">
							<button id="countDownSignForm"><?=/** @noEscape */__('Sign Up')?></button>
						</div>
					</div>
				</div>
			</div>

			<div class="mastheadsignform" style="display: none;" id="signform">
				<div class="container-fluid px-4 px-lg-0">

					<form name="addData" method="post" id="addData" class="form"
						data-hasrequired="<?=$block->escapeHtmlAttr(__('* Required Fields'))?>"
						data-mage-init='{"validation":{}}'>
						<fieldset class="fieldset">

							<fieldset class="fieldset row">
								<div class="fields inputGroupForm">
									<div class="field-heading"><h2> <?=/** @noEscape */__('SIGN UP')?></h2></div>
									<div class="field name required">
										<div class="control">
											<input name="email" id="email" title="Email" value="" class="input-text" type="text"
											data-validate="{required: true,'validate-email':true}"
											placeholder="<?=$block->escapeHtmlAttr(__('E-mail'))?>">
										</div>
									</div>
									<div class="field name required">
										<div class="control">
											<input name="telephone" id="telephone" title="Telephone" value="" class="input-text"
												type="text" data-validate="{'required': true,'digits':true}" placeholder="<?=$block->escapeHtmlAttr(__('Phone Number'))?>">
										</div>
									</div>
									<!-- Captcha -->
									<?=$block->getChildHtml('eighteentech.captchaform.captcha1');?>
								</div>
							</fieldset>
						</fieldset>
						<div class="actions-toolbar">
							<div class="primary">
								<button type="submit" class="action submit primary" title="Done" id="submitForm">
									<span><?=$block->escapeHtmlAttr(__('Done'))?></span>
								</button>
							</div>
						</div>
					</form>
				</div>

			</div>

			<div class="success-container" style="display: none;">
				<div class="customform-success">
					<div class="success-logo">
						<img src="<?=$this->getViewFileUrl('Eighteentech_CustomForm::images/image.png');?>" title="Gotcha"></div>
					<div class="success-title">
						<h2><?=/** @noEscape */__('Gotcha!')?> </h2>
					</div>
				</div>
			</div>
		</div>
		<div class="footer">
			<div class="container-fluid px-4 py-2">
				<ul class="footerItems">
					<li><a href="/privacy-policy"> <?=/** @noEscape */__('Privacy Policy')?> </a></li>
					<li><a href="/terms-conditions"> <?=/** @noEscape */__('Terms & Conditions')?></a></li>
				</ul>
			</div>
		</div>		
	</div>
</div>
<?php endif;?>

<script>

require(['jquery', 'jquery/ui','mage/url',], function($,url){
  jQuery(document).ready( function() {
    function makeTimer() {
        // var endTime = new Date("29 April 2018 9:56:00 GMT+01:00");
        var endTime = new Date("<?=$block->countDownDate()?>");
        endTime = (Date.parse(endTime) / 1000);

        var now = new Date();
        now = (Date.parse(now) / 1000);

        var timeLeft = endTime - now;

        var days = Math.floor(timeLeft / 86400);
        var hours = Math.floor((timeLeft - (days * 86400)) / 3600);
        var minutes = Math.floor((timeLeft - (days * 86400) - (hours * 3600 )) / 60);
        var seconds = Math.floor((timeLeft - (days * 86400) - (hours * 3600) - (minutes * 60)));

        if (hours < "10") { hours = "0" + hours; }
        if (minutes < "10") { minutes = "0" + minutes; }
        if (seconds < "10") { seconds = "0" + seconds; }

        $("#days").html(days +":"+ "<span>Days</span>");
        $("#hours").html(hours +":"+ "<span>Hours</span>");
        $("#minutes").html(minutes +":"+ "<span>Minutes</span>");
        $("#seconds").html(seconds + "<span>Seconds</span>");

    }setInterval(function() { makeTimer(); }, 1000);

	$("#countDownSignForm").click(function(){
		$("#comingSoonId").hide();
		$("#signform").show();
	});

	$('#addData').submit(function(e){
		var email = $("#email").val();
		var telephone = $("#telephone").val();
		var regEx = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;;
		var validEmail = regEx.test(email);
		var regExph = /^[0-9-+]+$/;
		var validPhone = regExph.test(telephone);
		if (validEmail && validPhone) {
			$("#signform").hide();
			$.ajax({
				type: "post",
				url: '<?=$this->getFormAction()?>',
				data: $("#addData").serialize(),
				showLoader: true,
				success: function (data) {
					$("#comingSoonId").hide();
					$(".success-container").show();
					console.log(data.json_data);
				},
				error: function (xhr, status, error) {
					console.error(xhr);
				}
			});
		}
	   e.preventDefault();
	});
  });
});

</script>
<style>
	.coming-soon h2 {
		color: #000;
		font-weight: revert;
		font-size: 18px;
	}
	#countDownSignForm{
		background: #000;
		color: #fff;
	}

	.first-dibs-section h1 {
		font-size: 55px !important;
		color: #000;
		font-weight: revert;
	}
	div#signform {
		width: 60%;
		background: #000;
		padding: 0 38px;
		margin-left: 108px;
	}
	.field-heading h2 {
		text-align: center;
		color: #fff;
	}
	button#submitForm {
		background: #fff;
		color: #000;
		padding-bottom: 10px;
		margin-bottom: 8px;
		margin-top: -19px;
	}
	input#email,input#telephone {
		border-radius: 19px;
	}
	.success-title h2 {
		font-size: 45px;
		color: #000;
		font-weight: revert;
	}
	.success-logo {
		margin-left: 27px;
	}

    .masthead {
        position: relative;
        z-index: 2;
        display: flex;
        justify-content: center;
        min-height: 100vh;
    }

    .masthead .masthead-content {
		position: relative;
		max-width: 80rem;
		padding-top: 0;
		display: grid;
		width:100%;

		align-items: center;
		grid-template-rows: 1fr 120px;
    }
    .masthead .masthead-content h1, .masthead .masthead-content .h1 {
		font-size: 2.5rem;
    }
    .masthead .masthead-content p {
		font-size: 1.8rem;
		display: grid;
		width: 100%;
		text-align: center;
		margin-bottom: 3rem;
    }
    .masthead .masthead-content p strong {
		font-weight: 700;
    }
    .masthead .masthead-content .input-group-newsletter input {
		height: auto;
		width: 100%;
		font-size: 1rem;
		padding: 1rem;
    }
    .masthead .masthead-content .input-group-newsletter button {
		font-size: 0.85rem;
		font-weight: 700;
		text-transform: uppercase;
		letter-spacing: 1px;
		padding: calc(1rem + 2px);
    }

    @media (min-width: 992px) {

		.masthead .masthead-content h1, .masthead .masthead-content .h1 {
			font-size:2.5rem;
		}

    }
    .logo{
        margin: auto;
        margin-bottom: 2rem;
        width: 100%;
        display: grid;
        float: none;
        max-width: 48rem;
    }
    .logo svg, .logo img{
		max-width: 100%;
    }


    /* footer */
    .footer {
		position: relative;
		padding: 5rem 0;
		margin-top: auto;
    }

    .footer:before {
		content: "";
		width: 100vw;
		margin-left: 50%;
		transform: translateX(-50%);
		background: #000000;
		height: 100%;
		position: absolute;
		top: 0;
    }

    .footer > div {
		position: relative;
		z-index: 2;
    }

    .footer .footerItems {
		padding: 0;
		margin: 0;
		justify-content: center;
		grid-gap: 2rem;
		display: grid;
		grid-auto-flow: column;
		list-style: none;
    }

    .footer .footerItems a {
		color: #ffffff;
		text-decoration: none;
    }

    .footer .footerItems li {
		position: relative;
		margin-bottom:0;
    }

    .footer .footerItems li:not(:last-child):after {
		content: "";
		height: 14px;
		width: 1px;
		position: absolute;
		right: -1rem;
		top: 0.3rem;
		background: #ffffff;
    }


    .mastheadInner .masthead-content {
		max-width: 60rem;
		margin: auto;
		padding: 0 1rem;
    }

    body {
		overflow-x: hidden;
    }

    .mastheadInner {
		padding: 2rem 0 0;
    }
    .inputGroupForm {
		display: grid;
		grid-template-columns: minmax(0, 1fr) minmax(0, 1fr) minmax(0, 1fr);
		grid-gap: 2rem;
	}

	.inputGroupForm .field { }

	.inputGroupForm .field input {
		height: auto;
		width: 100%;
		font-size: 1.6rem;
		padding: 1.5rem 1rem;
		font-weight: 400;
		line-height: 1.5;
		color: #000000;
		background-color: #fff;
		background-clip: padding-box;
		border: 1px solid #ced4da;
		-webkit-appearance: none;
		-moz-appearance: none;
		appearance: none;
		border-radius: 0.25rem;
		transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
	}

	.CommingsoonPage .fieldset {
		margin-bottom: 0;
	}

	.CommingsoonPage { }

	.CommingsoonPage .actions-toolbar {
		text-align: center;
		display: grid;
		justify-content: center;
		margin-bottom: 2rem;
	}

	.CommingsoonPage .actions-toolbar .action {
		color: #fff;
		background-color: #000000;
		border-color: #000000;
		border-radius: 0.25rem;
		transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
		font-size: 1.4rem;
		font-weight: 700;
		text-transform: uppercase;
		letter-spacing: 1px;
		padding: calc(1.5rem + 2px);
	}
	.column.main {
		padding-bottom: 0 !important;
	}
	.copyright{
		display:none;
	}
	.sections.nav-sections {
		display: none;
	}

	.masthead .masthead-content > div {
		width: 100%;
	}

	.field.captcha {
		grid-column-end: span 3;
	}

	.field.captcha .control.captcha {
		display: grid;
		grid-template-columns: max-content max-content;
		grid-gap: 3rem;
		align-items: center;
	}

	.CommingsoonPage .actions-toolbar {
		margin-top: 5rem;
	}
</style>
