<?php
    /**
     * @author 18th DigiTech Team
     * @copyright Copyright (c) 2022 18th DigiTech (https://www.18thdigitech.com)
     * @package Eighteentech_CustomForm
     */
?>
<div class="success-container">
    <div class="customform-success">
        <div class="success-logo">
            <img src="<?= $this->getViewFileUrl('Eighteentech_CustomForm::images/image.png'); ?>" title="Gotcha"></div>
        <div class="success-title">
            <h2><?=  /** @noEscape */ __('Gotcha!')?> </h2>
        </div>        
    </div>
</div>